### ISSUE TITLE
Need help with Firefox to run this code

### ISSUE THREAD

**Issue by cnayan** [RickStrahl-Content/WindowsAuthWithGroupsIssue#1]
Hi @RickStrahl 

Thanks for sharing the code. I traced this code from your blog, to the issue you raised (https://github.com/dotnet/aspnetcore/issues/14766) to here.

I am learning how to authenticate user using Kerberos & NTLM. Your code helps!

When I run it on IE 11 and Chrome ver 83.xx, it works perfectly. But on Firefox (ver 78.0), the user never authenticates successfully, even though the credentials are correct.

Do you have any insight why it could be so?

Thanks much!
Regards,
Nayan

**Comment by RickStrahl** [comment]
Read the post again - it talks about that very issue. You need to explicitly enable the right authentication provider configuration in FireFox otherwise Windows auth doesn't work.

**Comment by cnayan** [comment]
The same Firefox browser is able to authenticate for another WebApp using NTLM without browser configuration changed. That works, but not this. So I'm guessing code needs to change.

Also, your problem, as I understand, was resolved by rebooting the machine to clear cache.

I don't see this as my case here. If you can advise, I'll appreciate it much.

Thank you.

**Comment by cnayan** [comment]
I have read your blog post https://weblog.west-wind.com/posts/2019/Nov/14/FireFox-Windows-Security-and-Kestrel-on-ASPNET-Core and adjusted the config accordingly for Firefox.

Will observe the behavior of FF. Thanks!
